### PR TITLE
ENH add meg dataset

### PR DESCRIPTION
**Pull request by mathurinm**

### CODE REVIEW

**Review by agramfort — COMMENTED** [review]
every CI run will now download 2GB of data. If you don't cache anything that can be painful.

maybe we can push this X and y to openml and use sklearn fetch_openml?

**Comment by mathurinm** [comment]
Should I upload just X and y, or include both Right and Left auditory, and eventually return the full Y's too ?

Do you know if it's possible to include the preprocessing details on openML too ? Otherwise it's a bit cryptic (e.g. I may have made an error in the preprocessing)

**Comment by agramfort** [comment]
I would upload the full X and Y after whitening.

I would put the preprocessing code in the data description

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
@mathurinm merge if done. 🙏

**Comment by mathurinm** [comment]
thanks @agramfort

**Pull request merged**
