### PR TITLE
[WIP] Test fix rpy2 for PR 21

### PR DESCRIPTION
**Pull request by tanglef**
From #21 trying to find a fix for the CI

### CODE REVIEW

**Comment by tanglef** [comment]
Libgfortran 3 is installed, 5 too, but rpy2 wants to use libgfortran 4 with glmnet

**Comment by tanglef** [comment]
In the error log 
`
2021-03-21T17:12:12.5154938Z E   rpy2.rinterface_lib.embedded.RRuntimeError: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
2021-03-21T17:12:12.5156390Z E     unable to load shared object '/usr/share/miniconda/envs/bench_test_env/lib/R/library/glmnet/libs/glmnet.so':
2021-03-21T17:12:12.5157447Z E     libgfortran.so.4: cannot open shared object file: No such file or directory`

the path to `glmnet.so` actually exists (`ISOK` variable in the log)

**Comment by tanglef** [comment]
According to the log, libgfortran.4.so' path is /usr/local/julia1.5.4/lib/julia/libgfortran.so4

**Comment by tomMoral** [comment]
Closing in favor of #21 

Thanks for the investigation @tanglef !

**Pull request closed without merging**
