### PR TITLE
temporarily remove modopt as it breaks env creation

### PR DESCRIPTION
**Pull request by mathurinm**
They will release a new version where this is fixed around mid-december (https://github.com/CEA-COSMIC/ModOpt/issues/169).

 In the meantime, I propose to remove this solver as it's a pain to use benchopt commands when this one is present.

### CODE REVIEW

**Comment by agramfort** [comment]
@tomMoral can you just disable a solver with a local config file?

**Review by agramfort — APPROVED** [review]
let's proceed I agree

**Comment by tomMoral** [comment]
> @tomMoral can you just disable a solver with a local config file?

We used to have this feature but it was deemed too early and I removed it ^^'
I could add it back :)

**Comment by agramfort** [comment]
let's KISS

>

**Comment by tomMoral** [comment]
Not sure that this is simple and stupid to have to remove and re-add solver when the dependencies breaks instead of editing a file...

**Comment by tomMoral** [comment]
Agreed it is not the priority.

**Pull request merged**
